services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8000"
    environment:
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    restart: unless-stopped