name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 'v1.40.x'

      - name: Update deno.json
        run: |
          sed -i 's/"nodeModulesDir": "auto"/"nodeModulesDir": true/g' deno.json

      - name: Install dependencies
        run: deno cache --reload main.ts

      - name: Run tests
        run: deno test --allow-net --allow-env
