name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 'v1.40.x'

      - name: Remove existing lockfile
        # Temporarily remove lockfile only in CI environment due to compatibility issues
        # The actual lockfile remains in the repository for development consistency
        run: rm -f deno.lock

      - name: Update deno.json configuration
        run: |
          sed -i 's/"nodeModulesDir": "auto"/"nodeModulesDir": true/g' deno.json

      - name: Install dependencies
        run: deno cache main.ts

      - name: Run tests
        # Adding --no-check flag to match development environment behavior
        run: deno test --allow-net --allow-env --no-check
